version: '3.5'
services:

    shadowsocks:
        image: shadowsocks/shadowsocks-libev
        restart: always
        environment:
            PASSWORD: ${SHADOWSOCKS_PASSWORD}

    kcptun:
        build: kcptun/docker
        environment:
            KCPTUN_KEY: ${KCPTUN_KEY}
        ports:
            - "${KCPTUN_PORT}:29900/udp"
