version: '3.5'
services:

    shadowsocks:
        image: shadowsocks/shadowsocks-libev
        environment:
            PASSWORD: ${SHADOWSOCKS_PASSWORD}
        ports:
            - ${SHADOWSOCKS_PORT}:8388
            - ${SHADOWSOCKS_PORT}:8388/udp